# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/22f58b01-2c59-49bc-a287-b94003453388";
      fsType = "btrfs";
      options = [ "compress=lzo" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8598-2171";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d46945d8-3335-4adb-8b69-3f82e74b943b"; }
    ];

  nix.maxJobs = lib.mkDefault 1;
}
