{
 "title": "Alfeizerao Energy",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Simple", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"alfeizerao\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kostal_inverter_msf\" or r[\"_measurement\"] == \"kostal_inverter_raw\")\n  |> filter(fn: (r) => r[\"DeviceName\"] == \"PIKO 4.6-2 MP plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OwnConsumed_W\" or r[\"_field\"] == \"GridConsumed_W\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")\n  \n  "
    }
   ]
  },
  {
   "title": "Power Generation",
   "type": "timeseries",
   "description": "Photovoltaics generation",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"alfeizerao\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kostal_inverter_msf\")\n  |> filter(fn: (r) => r[\"DeviceName\"] == \"PIKO 4.6-2 MP plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OwnConsumed_W\" or r[\"_field\"] == \"GridInjected_W\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Commulative Measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Commulatvie GRID Power Consumed",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"alfeizerao\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kostal_inverter_msf\")\n  |> filter(fn: (r) => r[\"DeviceName\"] == \"PIKO 4.6-2 MP plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"GridConsumed_W\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  |> cumulativeSum()\n  |> yield()\n"
    }
   ]
  },
  {
   "title": "Commulative Solar Power Generation",
   "type": "stat",
   "description": "Kostal 4.6-2 MP Plus (Power Generation, raw data)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"alfeizerao\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kostal_inverter_raw\")\n  |> filter(fn: (r) => r[\"DeviceName\"] == \"PIKO 4.6-2 MP plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"AC_Power_W\" )\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  |> cumulativeSum()\n  |> yield()\n"
    }
   ]
  },
  {
   "title": "Commulative Solar Power Consumed",
   "type": "stat",
   "description": "Sum of Solar Power Generation that was utilized",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"alfeizerao\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kostal_inverter_msf\")\n  |> filter(fn: (r) => r[\"DeviceName\"] == \"PIKO 4.6-2 MP plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OwnConsumed_W\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  |> cumulativeSum()\n  |> yield()\n"
    }
   ]
  },
  {
   "title": "Commulative Wasted Solar Power Generation ",
   "type": "stat",
   "description": "All the Solar Power that we generated but had to \"injected on the grid\", because we didn't use.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"alfeizerao\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kostal_inverter_msf\")\n  |> filter(fn: (r) => r[\"DeviceName\"] == \"PIKO 4.6-2 MP plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"GridInjected_W\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  |> cumulativeSum()\n  |> yield()\n"
    }
   ]
  },
  { "title": "TODO?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "TODO",
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 39 },
   "options": {
    "content": "TODO\n\n 1. Consumption running sum\n 1. Solar consumption running sum\n 1. Grid consumption running sum"
   }
  },
  {
   "title": "Alfeizerao Total Power Consumption + Generation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"alfeizerao\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kostal_inverter_msf\")\n  |> filter(fn: (r) => r[\"DeviceName\"] == \"PIKO 4.6-2 MP plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TotalPower_W\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Raw metrics from Inverter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Kostal 4.6-2 MP Plus (Power, raw data)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"alfeizerao\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kostal_inverter_raw\")\n  |> filter(fn: (r) => r[\"DeviceName\"] == \"PIKO 4.6-2 MP plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OwnConsumedPower_W\" or r[\"_field\"] == \"GridInjectedPower_W\" or r[\"_field\"] == \"GridConsumedPower_W\" or r[\"_field\"] == \"AC_Power_W\" )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Kostal 4.6-2 MP Plus (Voltage, raw data)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"alfeizerao\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kostal_inverter_raw\")\n  |> filter(fn: (r) => r[\"DeviceName\"] == \"PIKO 4.6-2 MP plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"AC_Voltage_V\" or r[\"_field\"] == \"DC_Voltage1_V\" or r[\"_field\"] == \"DC_Voltage2_V\" or r[\"_field\"] == \"LINK_Voltage_V\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}