{
 "title": "Alfeizerao Energy - Summary",
 "time": { "from": "now-60d", "to": "now" },
 "panels": [
  { "title": "Simple", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"alfeizerao\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kostal_inverter_msf\" or r[\"_measurement\"] == \"kostal_inverter_raw\")\n  |> filter(fn: (r) => r[\"DeviceName\"] == \"PIKO 4.6-2 MP plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OwnConsumed_W\" or r[\"_field\"] == \"GridConsumed_W\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")\n  \n  "
    }
   ]
  },
  {
   "title": "Power Generation",
   "type": "timeseries",
   "description": "Photovoltaics generation",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"alfeizerao\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kostal_inverter_msf\")\n  |> filter(fn: (r) => r[\"DeviceName\"] == \"PIKO 4.6-2 MP plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OwnConsumed_W\" or r[\"_field\"] == \"GridInjected_W\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Commulative Measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Daily Grid Energy Consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"alfeizerao\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kostal_inverter_msf\")\n  |> filter(fn: (r) => r[\"DeviceName\"] == \"PIKO 4.6-2 MP plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"GridConsumed_W\" or r[\"_field\"] == \"OwnConsumed_W\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: true)\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\n  |> yield()\n"
    }
   ]
  },
  {
   "title": "Daily Solar Energy (Consumed vs Injected)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"alfeizerao\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kostal_inverter_msf\")\n  |> filter(fn: (r) => r[\"DeviceName\"] == \"PIKO 4.6-2 MP plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OwnConsumed_W\" or r[\"_field\"] == \"GridInjected_W\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: true)\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\n  |> yield()\n"
    }
   ]
  },
  {
   "title": "Daily Solar Energy Generation",
   "type": "timeseries",
   "description": "Energy produced (Watt/Hours) per day",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"alfeizerao\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kostal_inverter_raw\")\n  |> filter(fn: (r) => r[\"DeviceName\"] == \"PIKO 4.6-2 MP plus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"AC_Power_W\" )\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: true)\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\n  |> yield()"
    }
   ]
  }
 ]
}