# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2bcd97d5-5b8c-4882-959e-d2af3334ee47";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D693-A6F9";
      fsType = "vfat";
    };

  fileSystems."/media/weird" =
    { device = "weird";
      fsType = "zfs";
    };

  fileSystems."/media/weird/backups" =
    { device = "weird/backups";
      fsType = "zfs";
    };

  fileSystems."/media/weird/backups/caitlin" =
    { device = "weird/backups/caitlin";
      fsType = "zfs";
    };

  fileSystems."/media/weird/restic" =
    { device = "weird/restic";
      fsType = "zfs";
    };

  fileSystems."/media/weird/snapshots" =
    { device = "weird/snapshots";
      fsType = "zfs";
    };

  fileSystems."/media/weird/syncthing" =
    { device = "weird/syncthing";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/85b871e2-888c-468b-bfce-be4816daf224"; }
    ];

  nix.maxJobs = lib.mkDefault 2;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
