include /etc/sway/config

set $alt Mod1

input type:touchpad {
    tap enabled
    natural_scroll enabled
}

bindsym $mod+Return exec alacritty
bindsym $mod+Shift+Return exec firefox
bindsym $mod+d exec wmenu-run
bindsym $mod+space exec wmenu-run

bindsym $mod+Escape exec swaylock
bindsym --locked $mod+Shift+s exec systemctl suspend

bindsym $mod+Tab workspace next
bindsym $mod+Shift+Tab workspace prev
bindsym $mod+Ctrl+Tab workspace next_on_output
bindsym $mod+Ctrl+l workspace next_on_output
bindsym $mod+Ctrl+h workspace prev_on_output

bindsym $mod+Ctrl+a scratchpad show
bindsym $mod+Ctrl+m move to scratchpad

bindsym $mod+$alt+1 move container to workspace number 1; workspace number 1
bindsym $mod+$alt+2 move container to workspace number 2; workspace number 2
bindsym $mod+$alt+3 move container to workspace number 3; workspace number 3
bindsym $mod+$alt+4 move container to workspace number 4; workspace number 4
bindsym $mod+$alt+5 move container to workspace number 5; workspace number 5
bindsym $mod+$alt+6 move container to workspace number 6; workspace number 6
bindsym $mod+$alt+7 move container to workspace number 7; workspace number 7
bindsym $mod+$alt+8 move container to workspace number 8; workspace number 8
bindsym $mod+$alt+9 move container to workspace number 9; workspace number 9
bindsym $mod+$alt+0 move container to workspace number 10; workspace number 10

bindsym $mod+t layout toggle tabbed stacking splith splitv
bindsym $mod+Shift+t focus mode_toggle
bindsym $mod+f fullscreen toggle
bindsym $mod+Shift+f floating toggle
bindsym $mod+v split vertical
bindsym $mod+g split horizontal
bindsym $mod+BackSpace split toggle
