# Do not modify this file! It was generated by nixos-generate-config.
{ lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "ehci_pci"
    "firewire_ohci"
    "sd_mod"
    "sdhci_pci"
    "sr_mod"
    "uas"
    "uhci_hcd"
    "usb_storage"
    "usbhid"
    "xhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.initrd.systemd.enable = true;
  boot.kernelModules = [ "kvm-intel" "b43" ];
  boot.extraModulePackages = [ ];

  boot.supportedFilesystems = [ "zfs" "btrfs" ];
  boot.zfs.package = pkgs.zfs_unstable;
  boot.kernelParams = [
    "mitigations=off"
    "zfs.zfs_arc_max=2147483648"
  ];
  boot.kernel.sysctl."vm.swappiness" = 60;

  fileSystems."/" = {
    device = "rpool/root/nixos";
    fsType = "zfs";
  };
  fileSystems."/home" = {
    device = "rpool/home";
    fsType = "zfs";
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0297-90C1";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };
  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    enableRedistributableFirmware = true;
    firmware = [ pkgs.b43Firmware_6_30_163_46 ];
    cpu.intel.updateMicrocode = true;
    graphics = {
      enable = true;
      extraPackages = [ pkgs.intel-vaapi-driver ];
    };
  };

  networking.hostId = "b05e6b14";
  networking.hostName = "margiehamilton";
  networking.networkmanager.enable = true;
  networking.useDHCP = lib.mkDefault false;
  networking.interfaces.enp2s0f0.useDHCP = lib.mkDefault true;

  nix.settings.max-jobs = lib.mkDefault 2;
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
