# Generated by nixos-generate-config, then trimmed.
{ config, lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.initrd.systemd.enable = true;
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/pompom--vg-nixos";
    fsType = "ext4";
  };
  fileSystems."/home" = {
    device = "/dev/mapper/pompom--vg-home";
    fsType = "ext4";
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/92FE-6312";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };
  swapDevices = [ { device = "/dev/mapper/pompom--vg-swap"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    enableRedistributableFirmware = true;
    cpu.intel.updateMicrocode = config.hardware.enableRedistributableFirmware;
    graphics.enable = true;
  };

  networking.hostName = "t460";
  networking.networkmanager.enable = true;
  networking.useDHCP = lib.mkDefault false;

  nix.settings.max-jobs = lib.mkDefault 4;
}
