# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "ehci_pci" "usbhid" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4c45c2d0-8481-4ba4-beb7-840ed287adc0";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3B4D-A22D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/824e7491-b494-4183-b2da-901ee8a20465"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    enableRedistributableFirmware = true;
    cpu.intel.updateMicrocode = true;
  };

  boot.supportedFilesystems = [ "zfs" "btrfs" ];
  boot.zfs.package = pkgs.zfs_unstable;
  boot.kernelPackages = pkgs.zfs.latestCompatibleLinuxPackages;
  boot.kernelParams = [
    # "mitigations=off"  # old b0x, need moar sp33d
  ];

  networking.hostName = "x99"; # Define your hostname.
  networking.hostId = "a7ec8faa"; # zfs needs this
  # Pick only one of the below networking options.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.
  # networking.networkmanager.enable = true;  # Easiest to use and most distros use this by default.

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault false;
  networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  #networking.interfaces.wlp3s0.useDHCP = true;
  networking.interfaces.enp6s0.ipv4.addresses = [
  { # alfeizerao
    address = "192.168.0.14";
    prefixLength = 16;
  }
  { # backup for lisbon
    address = "192.168.1.24"; 
    prefixLength = 16;
  }
  ];
}
